### PR TITLE
Fixes pool assets row detail render

### PR DESCRIPTION
**Pull request by qiqicodes**
- [x] fixes pool assets row detail render, when pyth price data is unavailable
- [x] fixes fmt 
- [x] strikes out texts for stale pool
- [x] provides the ema price for stale pool

### CODE REVIEW

**Comment by davodesign84** [comment]
Currently some discord users have been told to reference missing token details to identify stale pools that can not be transacted on. This PR takes this away from them. How about some strike out text or some other identifier that tells them if a pool is currently unable to be transacted on?

**Comment by KevinRafaelConnor** [comment]
@davodesign84 How do you like this styling for stale pools? I am working on a pull request to merge into this one at #460 

image

**Comment by davodesign84** [comment]
Yeah I think that's better, would be great to add a warning/ tooltip explaining why they are temporarily  disabled

Sent from Yahoo Mail on Android 
 
  On Wed, 16 Nov 2022 at 18:47, ***@***.***> wrote:   


@davodesign84 How do you like this styling for stale pools? I am working on a pull request to merge into this one at #460

**Review by davodesign84 — DISMISSED** [review]

**Comment by KevinRafaelConnor** [comment]
@davodesign84 here's an updated screenshot showing the tooltip:
image
If you're alright with this and don't have any changes I'll merge my draft PR it into this branch. I do welcome feedback and changes to make it better like we talked about, ofc

**Pull request merged**
